### ISSUE TITLE
[Bug]: habana_main - Qwen2-7B fail on graph compile failed.

### ISSUE THREAD

**Issue by Zjq9409** [HabanaAI/vllm-fork#232]
### Your current environment
driver 1.17
vllm                              0.5.3.post1+gaudi117
```text
export VLLM_GRAPH_RESERVED_MEM=0.1
export VLLM_GRAPH_PROMPT_RATIO=0.9
export VLLM_PROMPT_SEQ_BUCKET_MIN=2048
export VLLM_PROMPT_SEQ_BUCKET_STEP=2048
export VLLM_PROMPT_SEQ_BUCKET_MAX=2048

export VLLM_PROMPT_BS_BUCKET_MIN=100
export VLLM_PROMPT_BS_BUCKET_STEP=100
export VLLM_PROMPT_BS_BUCKET_MAX=100

export VLLM_DECODE_SEQ_BUCKET_MIN=2048
export VLLM_DECODE_SEQ_BUCKET_STEP=2048
export VLLM_DECODE_SEQ_BUCKET_MAX=2560
export VLLM_DECODE_BS_BUCKET_MIN=100
export VLLM_DECODE_BS_BUCKET_STEP=100
export VLLM_DECODE_BS_BUCKET_MAX=100
export VLLM_ENGINE_ITERATION_TIMEOUT_S=100

export PT_HPU_RECIPE_CACHE_CONFIG=./cached_recipes,false,5000
export VLLM_PROMPT_USE_FUSEDSDPA=1


python -m vllm.entrypoints.openai.api_server \
  --model /data/Qwen2-7B-Instruct/ \
  --trust-remote-code \
  --tensor-parallel-size 1 \
  --block-size 128 \
  --dtype bfloat16 \
  --max-num-seqs 128 \
  --gpu-memory-utilization 0.9 \
  --disable-log-requests \
  --host 0.0.0.0 \
  --port 8111
```

### 🐛 Describe the bug

```
INFO 09-03 07:45:49 habana_model_runner.py:486] Loading model weights took in total 14.21 GiB of device memory (14.22 GiB/93.55 GiB used) and 1.984 GiB of host memory (48.26 GiB/1007 GiB used)
[rank0]: Traceback (most recent call last):
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/entrypoints/openai/api_server.py", line 312, in <module>
[rank0]:     asyncio.run(run_server(args))
[rank0]:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
[rank0]:     return loop.run_until_complete(main)
[rank0]:   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
[rank0]:     return future.result()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/entrypoints/openai/api_server.py", line 289, in run_server
[rank0]:     app = await init_app(args, llm_engine)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/entrypoints/openai/api_server.py", line 229, in init_app
[rank0]:     if llm_engine is not None else AsyncLLMEngine.from_engine_args(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/engine/async_llm_engine.py", line 479, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/engine/async_llm_engine.py", line 380, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/engine/async_llm_engine.py", line 560, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/engine/llm_engine.py", line 266, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/engine/llm_engine.py", line 365, in _initialize_kv_caches
[rank0]:     self.model_executor.determine_num_available_blocks())
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/executor/habana_executor.py", line 77, in determine_num_available_blocks
[rank0]:     return self.driver_worker.determine_num_available_blocks()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/worker/habana_worker.py", line 142, in determine_num_available_blocks
[rank0]:     self.model_runner.profile_run()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/worker/habana_model_runner.py", line 1090, in profile_run
[rank0]:     self.warmup_scenario(max_batch_size,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/worker/habana_model_runner.py", line 1152, in warmup_scenario
[rank0]:     self.execute_model(inputs, kv_caches, warmup_mode=True)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/worker/habana_model_runner.py", line 1612, in execute_model
[rank0]:     output = self.model.sample(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/worker/habana_model_runner.py", line 205, in sample
[rank0]:     return self.model.sample(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/model_executor/models/qwen2.py", line 359, in sample
[rank0]:     next_tokens = self.sampler(logits, sampling_metadata)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1535, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1585, in _call_impl
[rank0]:     result = forward_call(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/model_executor/layers/sampler.py", line 138, in forward
[rank0]:     sample_results, maybe_sampled_tokens_tensor = _sample(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/model_executor/layers/sampler.py", line 712, in _sample
[rank0]:     return _sample_with_torch(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/model_executor/layers/sampler.py", line 593, in _sample_with_torch
[rank0]:     sample_results = _greedy_sample(seq_groups, greedy_samples)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm-0.5.3.post1+gaudi117-py3.10.egg/vllm/model_executor/layers/sampler.py", line 336, in _greedy_sample
[rank0]:     print("jane samples :", samples)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 474, in __repr__
[rank0]:     return torch._tensor_str._str(self, tensor_contents=tensor_contents)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 697, in _str
[rank0]:     return _str_intern(self, tensor_contents=tensor_contents)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 617, in _str_intern
[rank0]:     tensor_str = _tensor_str(self, indent)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 349, in _tensor_str
[rank0]:     formatter = _Formatter(get_summarized_data(self) if summarize else self)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 133, in __init__
[rank0]:     value_str = f"{value}"
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 1000, in __format__
[rank0]:     return self.item().__format__(format_spec)
[rank0]: RuntimeError: Graph compile failed. synStatus=synStatus 26 [Generic failure]. 
```

**Comment by xuechendi** [comment]
@Zjq9409 , what is the test_message? I tested with exact same branch w/ same env var and serving settings, it went through successfully.

![image](https://github.com/user-attachments/assets/0a9c2d3b-e8fd-4327-a559-b9d0246c993b)

![image](https://github.com/user-attachments/assets/11120eb8-6ddd-4d9e-9a25-39d6c1c5c55d)
![image](https://github.com/user-attachments/assets/fe8fc364-1281-4bac-8853-1b26b7c85ca3)

``` test_openai_sdk_qwen.py
from openai import OpenAI

if __name__ == "__main__":
    
    model = "Qwen/Qwen2-7B-Instruct"
    #model = "meta-llama/Meta-Llama-3.1-8B-Instruct"
    llm = OpenAI(base_url="http://100.83.111.250:8000/v1", api_key="EMPTY")
    
    input = [{"role": "user", "content": "你是谁？"}]
    
    output = llm.chat.completions.create(
        model=model,
        messages=input,
        stream=True,
        max_tokens=128,
    )
    
    for chunk in output:
        if cont := chunk.choices[0].delta.content:
            print(cont, end='', flush=True)
            
    print()
```

**Comment by xuechendi** [comment]
@Zjq9409 , I didn't see "VLLM_PROMPT_USE_FUSEDSDPA" enabled in "v0.5.3.post1-Gaudi-1.17.0". If you would like to test with FusedSDPA, may need to switch to "habana_main" branch

**Comment by Zjq9409** [comment]
> serving

I tested it using habana-main

**Comment by Zjq9409** [comment]
> @Zjq9409 , what is the test_message? I tested with exact same branch(v0.5.3.post1-Gaudi-1.17.0) w/ same env var and serving settings, it went through successfully.
> 
> ![image](https://private-user-images.githubusercontent.com/4355494/364857945-0a9c2d3b-e8fd-4327-a559-b9d0246c993b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODU0NzUsIm5iZiI6MTcyNTg4NTE3NSwicGF0aCI6Ii80MzU1NDk0LzM2NDg1Nzk0NS0wYTljMmQzYi1lOGZkLTQzMjctYTU1OS1iOWQwMjQ2Yzk5M2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDlUMTIzMjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2VlZjMwYzA2YjIxZWIzODY0YmIxNDZjN2FjMWZhOGU2NTNiYzA2MzU3YmMxOTYwMTJjZjYyN2ZmZjZjOGQ0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5RguK-I1c1oYbm1p1nxwvGX3MlSVQ6b0SdlTpmwLljM)
> 
> ![image](https://private-user-images.githubusercontent.com/4355494/364857691-11120eb8-6ddd-4d9e-9a25-39d6c1c5c55d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODU0NzUsIm5iZiI6MTcyNTg4NTE3NSwicGF0aCI6Ii80MzU1NDk0LzM2NDg1NzY5MS0xMTEyMGViOC02ZGRkLTRkOWUtOWEyNS0zOWQ2YzFjNWM1NWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDlUMTIzMjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjAxMTMwOGMyNjI1MGRhZTNmYTc3NzU4NDJjZmJiNmEzMGQyOWNmZWNlZGVlZjA5NDQ2MWE4N2IyNTYwMDU3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KrBlbX5b9Ye51bnt48J3ukXgVy-wVg8PPyifeTEl2B4) ![image](https://private-user-images.githubusercontent.com/4355494/364857835-fe8fc364-1281-4bac-8853-1b26b7c85ca3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODU0NzUsIm5iZiI6MTcyNTg4NTE3NSwicGF0aCI6Ii80MzU1NDk0LzM2NDg1NzgzNS1mZThmYzM2NC0xMjgxLTRiYWMtODg1My0xYjI2YjdjODVjYTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDlUMTIzMjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzA4MjdiMDg0MzM5MzZmOGQzNzU5ZDUzMzc2YTE2MTAyYjU4NDVkODRhZmU3ZGIwZTRlMWQxMDkxMDkwYzgwOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4ULOEVuRFPkEMeO26dKbLHdqhbrgnwzJMLpzcfVKGhU)
> 
> ```python
> from openai import OpenAI
> 
> if __name__ == "__main__":
>     
>     model = "Qwen/Qwen2-7B-Instruct"
>     #model = "meta-llama/Meta-Llama-3.1-8B-Instruct"
>     llm = OpenAI(base_url="http://100.83.111.250:8000/v1", api_key="EMPTY")
>     
>     input = [{"role": "user", "content": "你是谁？"}]
>     
>     output = llm.chat.completions.create(
>         model=model,
>         messages=input,
>         stream=True,
>         max_tokens=128,
>     )
>     
>     for chunk in output:
>         if cont := chunk.choices[0].delta.content:
>             print(cont, end='', flush=True)
>             
>     print()
> ```

which branch are you use?

**Comment by xuechendi** [comment]
> > serving
> 
> I tested it using habana-main

according to the log you provided, you're testing on 'vllm-0.5.3.post1+gaudi117', which is behind habana-main. And are you testing on G2D or G2H?

BTW, I tested on both habana_main and the exact same branch (vllm-0.5.3.post1+gaudi117). Both works ok on QWen2-7B with same configuration on G2H.

**Comment by michalkuligowski** [comment]
Hi @Zjq9409 do you still observer the issue or can it be closed?

**Comment by michalkuligowski** [comment]
Closing due to no update from author, please open if issue occurs on latest version
