### ISSUE TITLE
[Bug]: How to support long sequence?

### ISSUE THREAD

**Issue by Zjq9409** [HabanaAI/vllm-fork#257]
### Your current environment

model: Qwen2-7B
input_length: 16384, 30720
batch_size: 1,5,10,20,50

### 🐛 Describe the bug

how use habana vllm to support long sequence?

my serving script
```
export VLLM_GRAPH_RESERVED_MEM=0.1
export VLLM_GRAPH_PROMPT_RATIO=0.8
export VLLM_SKIP_WARMUP=true
 
python -m vllm.entrypoints.openai.api_server \
  --model ./Qwen2-7B-Instruct/ \
  --trust-remote-code \
  --tensor-parallel-size 1 \
  --block-size 128 \
  --dtype bfloat16 \
  --max-num-seqs 128 \
  --gpu-memory-utilization 0.9 \
  --host 0.0.0.0 \
  --port 8117
```

my long sequence client test script
```
for bsize in 1 2 4 8; do
  echo "benchmark serving bs${bsize}"
  python benchmark_serving.py \
    --backend vllm \
    --model /home/jane/Qwen2-7B-Instruct/ \
    --trust-remote-code \
    --dataset-name random \
    --random-input-len 16384 \
    --random-output-len 512 \
    --num-prompts ${bsize} \
    --request-rate inf \
    --port 8117
  sleep 20
done
```

my error log
```
INFO 09-10 02:01:33 metrics.py:334] Avg prompt throughput: 1849.6 tokens/s, Avg generation throughput: 2.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 7 reqs, GPU KV cache usage: 3.6%, CPU KV cache usage: 0.0%
INFO 09-10 02:01:41 metrics.py:334] Avg prompt throughput: 4282.8 tokens/s, Avg generation throughput: 0.3 tokens/s, Running: 3 reqs, Swapped: 0 reqs, Pending: 5 reqs, GPU KV cache usage: 10.3%, CPU KV cache usage: 0.0%
INFO 09-10 02:01:49 metrics.py:334] Avg prompt throughput: 4237.0 tokens/s, Avg generation throughput: 0.2 tokens/s, Running: 5 reqs, Swapped: 0 reqs, Pending: 3 reqs, GPU KV cache usage: 17.2%, CPU KV cache usage: 0.0%
INFO 09-10 02:01:55 metrics.py:334] Avg prompt throughput: 3194.2 tokens/s, Avg generation throughput: 0.2 tokens/s, Running: 7 reqs, Swapped: 0 reqs, Pending: 1 reqs, GPU KV cache usage: 23.9%, CPU KV cache usage: 0.0%
ERROR 09-10 02:01:57 async_llm_engine.py:43] Engine background task failed
ERROR 09-10 02:01:57 async_llm_engine.py:43] Traceback (most recent call last):
ERROR 09-10 02:01:57 async_llm_engine.py:43]   File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/engine/async_llm_engine.py", line 38, in _raise_exception_on_finish
ERROR 09-10 02:01:57 async_llm_engine.py:43]     task.result()
ERROR 09-10 02:01:57 async_llm_engine.py:43]   File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/engine/async_llm_engine.py", line 509, in run_engine_loop
ERROR 09-10 02:01:57 async_llm_engine.py:43]     has_requests_in_progress = await asyncio.wait_for(
ERROR 09-10 02:01:57 async_llm_engine.py:43]   File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
ERROR 09-10 02:01:57 async_llm_engine.py:43]     return fut.result()
ERROR 09-10 02:01:57 async_llm_engine.py:43]   File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/engine/async_llm_engine.py", line 483, in engine_step
ERROR 09-10 02:01:57 async_llm_engine.py:43]     request_outputs = await self.engine.step_async()
ERROR 09-10 02:01:57 async_llm_engine.py:43]   File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/engine/async_llm_engine.py", line 221, in step_async
ERROR 09-10 02:01:57 async_llm_engine.py:43]     output = await self.model_executor.execute_model_async(
ERROR 09-10 02:01:57 async_llm_engine.py:43]   File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/executor/habana_executor.py", line 147, in execute_model_async
ERROR 09-10 02:01:57 async_llm_engine.py:43]     output = await make_async(self.driver_worker.execute_model
ERROR 09-10 02:01:57 async_llm_engine.py:43]   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
ERROR 09-10 02:01:57 async_llm_engine.py:43]     result = self.fn(*self.args, **self.kwargs)
ERROR 09-10 02:01:57 async_llm_engine.py:43]   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ERROR 09-10 02:01:57 async_llm_engine.py:43]     return func(*args, **kwargs)
ERROR 09-10 02:01:57 async_llm_engine.py:43]   File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/worker/habana_worker.py", line 244, in execute_model
ERROR 09-10 02:01:57 async_llm_engine.py:43]     output = self.model_runner.execute_model(seq_group_metadata_list,
ERROR 09-10 02:01:57 async_llm_engine.py:43]   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
ERROR 09-10 02:01:57 async_llm_engine.py:43]     return func(*args, **kwargs)
ERROR 09-10 02:01:57 async_llm_engine.py:43]   File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/worker/habana_model_runner.py", line 1039, in execute_model
ERROR 09-10 02:01:57 async_llm_engine.py:43]     hidden_states = self.model.forward(**execute_model_kwargs, selected_token_indices=sampling_metadata.selected_token_indices)
ERROR 09-10 02:01:57 async_llm_engine.py:43]   File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 724, in forward
ERROR 09-10 02:01:57 async_llm_engine.py:43]     return wrapped_hpugraph_forward(
ERROR 09-10 02:01:57 async_llm_engine.py:43]   File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 643, in wrapped_hpugraph_forward
ERROR 09-10 02:01:57 async_llm_engine.py:43]     cached.graph.replayV3(input_tensor_list, cached.asynchronous)
ERROR 09-10 02:01:57 async_llm_engine.py:43]   File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 76, in replayV3
ERROR 09-10 02:01:57 async_llm_engine.py:43]     _hpu_C.replayV3(self.hpu_graph, tlistI, asynchronous)
ERROR 09-10 02:01:57 async_llm_engine.py:43] RuntimeError: [Rank:0] FATAL ERROR :: MODULE:PT_SYNHELPER workspace Allocation of size ::52561502464 failed!
Exception in callback functools.partial(<function _raise_exception_on_finish at 0x7f68ee321360>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_engine.AsyncLLMEngine object at 0x7f68e33564d0>>)
handle: <Handle functools.partial(<function _raise_exception_on_finish at 0x7f68ee321360>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_engine.AsyncLLMEngine object at 0x7f68e33564d0>>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/engine/async_llm_engine.py", line 38, in _raise_exception_on_finish
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/engine/async_llm_engine.py", line 509, in run_engine_loop
    has_requests_in_progress = await asyncio.wait_for(
  File "/usr/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/engine/async_llm_engine.py", line 483, in engine_step
    request_outputs = await self.engine.step_async()
  File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/engine/async_llm_engine.py", line 221, in step_async
    output = await self.model_executor.execute_model_async(
  File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/executor/habana_executor.py", line 147, in execute_model_async
    output = await make_async(self.driver_worker.execute_model
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/worker/habana_worker.py", line 244, in execute_model
    output = self.model_runner.execute_model(seq_group_metadata_list,
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/worker/habana_model_runner.py", line 1039, in execute_model
    hidden_states = self.model.forward(**execute_model_kwargs, selected_token_indices=sampling_metadata.selected_token_indices)
  File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 724, in forward
    return wrapped_hpugraph_forward(
  File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 643, in wrapped_hpugraph_forward
    cached.graph.replayV3(input_tensor_list, cached.asynchronous)
  File "/usr/local/lib/python3.10/dist-packages/habana_frameworks/torch/hpu/graphs.py", line 76, in replayV3
    _hpu_C.replayV3(self.hpu_graph, tlistI, asynchronous)
RuntimeError: [Rank:0] FATAL ERROR :: MODULE:PT_SYNHELPER workspace Allocation of size ::52561502464 failed!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.10/dist-packages/vllm-0.4.2+gaudi117-py3.10.egg/vllm/engine/async_llm_engine.py", line 45, in _raise_exception_on_finish
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
INFO 09-10 02:01:57 async_llm_engine.py:154] Aborted request cmpl-28db24b7e07544ac9c1452c923550f73-0.
INFO 09-10 02:01:57 async_llm_engine.py:154] Aborted request cmpl-5ca05f00b5e64b438b9b9d0aeaf20b4d-0.
INFO 09-10 02:01:57 async_llm_engine.py:154] Aborted request cmpl-a11e15b6a7f94260a564a319c1226393-0.
INFO 09-10 02:01:57 async_llm_engine.py:154] Aborted request cmpl-59ce42dfd83546528dbe4d7044dfe9eb-0.
INFO 09-10 02:01:57 async_llm_engine.py:154] Aborted request cmpl-e3953e7508c9449294694a41defdcaad-0.
INFO 09-10 02:01:57 async_llm_engine.py:154] Aborted request cmpl-73b59f58c7054538a56bef238eb73dd8-0.
INFO 09-10 02:01:57 async_llm_engine.py:154] Aborted request cmpl-22ecd74be85f464cab8f3aa3e977411b-0.
INFO 09-10 02:01:57 async_llm_engine.py:154] Aborted request cmpl-5667be62f6554dc0a2f63590badc3b28-0.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 265, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 261, in wrap
    await func()
  File "/usr/local/lib/python3.10/dist-packages/starlette/responses.py", line 238, in listen_for_disconnect
    message = await receive()
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 555, in receive
    await self.message_event.wait()
  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f66f0a2d690

During handling of the above exception, another exception occurred:

```

**Comment by Zjq9409** [comment]
> ### Your current environment
> model: Qwen2-7B input_length: 16384, 30720 batch_size: 1,5,10,20
> 
> ### 🐛 Describe the bug
> how use habana vllm to support long sequence?

use which branch? how to set warm up parameter?

**Comment by vishnumadhu365** [comment]
@kzawora-intel facing similar issue with other models too (llama 3.1 8B, bs/num prompts =35, i/p 2048, o/p 128), known issue ?

**Comment by vishnumadhu365** [comment]
@Zjq9409  @pranjalst  if not already on the release tag, please try with this tag --> v0.5.3.post1+Gaudi-1.18.0

**Comment by michalkuligowski** [comment]
@Zjq9409 @pranjalst do you observe the issue, using instruction from [@vishnumadhu365](https://github.com/HabanaAI/vllm-fork/issues/257#issuecomment-2413548759) ?

**Comment by michalkuligowski** [comment]
Closing due to no update from the reporter, if issue occurs on latest release please file a ticket
